    // Generated by https://quicktype.io

export interface IMovieDBResponse {
    dates?:         IDates;
    page:          number;
    results:       IMovie[];
    total_pages:   number;
    total_results: number;
}

export interface IDates {
    maximum: string;
    minimum: string;
}

export interface IMovie {
    adult:             boolean;
    backdrop_path:     string;
    genre_ids:         number[];
    id:                number;
    original_language: IOriginalLanguage;
    original_title:    string;
    overview:          string;
    popularity:        number;
    poster_path:       string;
    release_date:      string;
    title:             string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
}

export enum IOriginalLanguage {
    En = "en",
    Fr = "fr",
    Es = "es",
}
